version: 2.1
jobs:
  build/test:
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
        command: npm run compile
      - run:
        command: jest
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - test
        filters:
          branches:
            only: 
              - master
