version: 2.1
jobs:
  build-test:
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run compile
      - store_artifacts: out
      - store_test_results: out
      - run: npm run test
orbs:
  node: circleci/node@3.0.0
workflows:
  dbutils-build:
    jobs:
      - build-test:
        filters:
          branches:
            only: 
              - master
