version: 2.1
jobs:
  build-test:
    docker: 
      - image: circleci/node:latest
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: dev
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install postgresql
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Running Test
          command: |
            psql -c "create database test" -U postgres
      - run: psql < src/test/sample-db/dvdrental/restore.sql
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run compile
      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit
      - run:
          name: Run tests with JUnit as reporter
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
orbs:
  node: circleci/node@3.0.0
workflows:
  dbutils-build:
    jobs:
      - build-test:
        filters:
          branches:
            only: 
              - master
