# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dvdrental
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install Postgres CLI
        run: |
          apt-get update -y
          apt-get install -y libpq-dev postgresql-client
        
      - name: Populate dvdrental Database 
        run: psql -d dvdrental -f src/test/sample-db/dvdrental/restore.sql
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTEGRES_HOST: 127.0.0.1
          POSTGRES_DB: dvdrental
  
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - uses: c-hive/gha-npm-cache@v1

      - name: Install npm dependencies
        run: npm install

          
        
      - name: Run tests with JUnit as reporter
        run: npm run test:ci
        env:
          JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
