# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:
    tags:
      - v*
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dvdrental
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:       
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: c-hive/gha-npm-cache@v1

      - name: Install npm dependencies
        run: npm install
        
      - name: Compile Package
        run: npm run compile
        
      - name: Populate dvdrental Database
        run: psql -d postgresql://postgres@localhost/dvdrental -f restore.sql
        working-directory: ./src/test/sample-db/dvdrental
        env:
          PGPASSWORD: postgres
          CI_ENV: true
        
      - name: Run tests with JUnit as reporter
        run: npm run test:ci
        env:
          JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
          PGPASSWORD: postgres,
          PGUSER: postgres

      - name: Upload build for use in test and deploy
        uses: actions/upload-artifact@v2
        with:
          name: pg-db-utils_build_latest
          path: ./out
          
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'create'
    needs: test
    steps:      
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Download latest build artifact
        uses: actions/download-artifact@v2
        with:
          name: pg-db-utils_build_latest
          path: ./out

      - name: Add NPM AUTH TOKEN to the .npmrc because of Github Actions bug
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
  
      - name: Publish latest version of pg-db-utils
        run: npm publish --access public
